[package]
name = "buddhabrot"
version = "0.1.0"
authors = ["Caleb Jones <code@calebjones.net>"]

[dependencies]
image = "0.10"
sdl2 = "0.25"
rand = "0.3"
bincode = "0.6"
flate2 = "0.2"
rustc-serialize = "0.3.21"
toml = "0.2"
